googleCal:
  creds:
    location: s3
    bucket: ${GOOGLE_CAL_CREDS_BUCKET}
    key: ${GOOGLE_CAL_CREDS_KEY}
  calendarId: primary

sns:
  myTopicArn: ${MY_TOPIC_ARN}

parse:
  primaryRecipient: ${PARSE_PRIMARY_RECIPIENT}

tokenUpdate:
  expectedSender: ${TOKEN_UPDATE_EXPECTED_SENDER}
  expectedSubject: ${TOKEN_UPDATE_EXPECTED_SUBJECT}
  tokenDestination:
    location: s3
    bucket: ${CLUB_LOCKER_TOKEN_BUCKET}
    key: ${CLUB_LOCKER_TOKEN_KEY}
