clubLocker:
  token:
    location: s3
    bucket: ${CLUB_LOCKER_TOKEN_BUCKET}
    key: ${CLUB_LOCKER_TOKEN_KEY}
  email: ${CLUB_LOCKER_EMAIL}

sns:
  myTopicArn: ${MY_TOPIC_ARN}
  publicTopicArn: ${PUBLIC_TOPIC_ARN}

dynamoDb:
  squashSlotsTableName: ${SLOTS_MONITORING_TABLE}
